apiVersion: v1
entries:
  portfolio:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-03-11T15:57:21.93077408Z"
    description: A Helm chart for Kubernetes
    digest: 46edcde05780239e10a4e0fe080cb0542e21f0ced4ce39348db3f4bfac06e237
    name: portfolio
    type: application
    urls:
    - https://gologolo24.github.io/Chart/portfolio-1.0.3.tgz
    version: 1.0.3
generated: "2025-03-11T15:57:21.929603942Z"
